server:
  port: 3002

spring:
  application:
    name: oauth2-cloud-auth-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      ## 注册中心配置
      discovery:
        # nacos的服务地址，nacos-server中IP地址:端口号
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.01
    password:
    port: 6379
    timeout: 15000
    jedis:
      pool:
        max-active: 600
        max-idle: 300
        max-wait: 15000
        min-idle: 10